# Generated by Django 5.0.6 on 2024-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
